### ISSUE TITLE
v4 requirements gathering thread

### ISSUE THREAD

**Issue by jcelerier** [jcelerier/libremidi#70]
Hello,
for anyone interested I'd like to pin this issue to discuss proposed API changes and reworks in a future version.

It'll be in this branch : https://github.com/jcelerier/libremidi/tree/v4

- [x] C++20 as minimum, unconditionally enable `<span>`, etc.
- [x] Refactor the library classes in individual files to make everything easier to edit
- [x] #73
  - [x] ALSA -> not available yet on a released ALSA version it seems
  - [x] CoreMIDI
  - [ ] Win32
- [x] Refactor the various individual queues, semaphores and threading objects used across the backends.
  - [x] custom semaphore -> std::semaphore
  - [x] pthread -> std::thread 
- [x] ~Enable configuring a custom queue type through some config.hpp~ -> now unnecessary, queue API has been removed as it can be built more efficiently on top of `libremidi::midi_in` in user code.
- [x] Allow to construct specific MIDI APIs with a specific context object (for instance passing an existing jack_client_t to midi_in_jack, etc) to enable to integrate more easily against existing run-loops - would fix #62 and also the macOS MIDIClient issue which required a singleton in rtmidi
   - mainly this also imply that we need to move the ability to execute the run-loop methods outside of the library if necessary, e.g. to run inside the user's existing audio callback?
   - [x] alsa raw
   - [x] alsa seq
   - [x] jack
   - [x] coremidi
   - [x] emscripten? -> it's global anyways
   - [x] uwp? -> it's global anyways
- [x] Instead of passing various "varying" arguments & calling member functions before init, simply have a single "configuration" struct passed to the ctor:  > done! see reworked examples in the branch

```c++
struct jack_in_conf {
  std::string_view client_name;
  void* context; // e.g. an existing jack or pipewire client
  int queue_size;
  int buffer_size;
};

struct configuration { 
  api_configuration api; // std::variant<jack_in_conf, alsa_in_conf, etc...>;

  chunking_parameters chunks;

  bool ignore_sysex; 
  bool ignore_time;
  bool ignore_sense;
};

libremidi::midi_in mid{ configuration {
  .api = jack_api_configuration { 
    .client_name = "foo" 
   }
 , .ignore_time = true 
}};
```
- [x] timestamps double -> int(64?) in `libremidi::message` #68  (done)
- [x] timestamps in nanoseconds everywhere
- [x] allow to choose whether we want timestamps and in which format (relative, or absolute with e.g. monotonic clock)
- [ ] `std::function_ref` support if available? 
- [x] finding a better way to name devices to prevent name conflicts. Ideally we would use something like libusb if available to get some proprely unique identifier (#57 #17)
- [ ] pipewire backend - I have experience with the audio part as I developed a back-end for ossia here: https://github.com/ossia/libossia/blob/master/src/ossia/audio/pipewire_protocol.hpp
- [x] remove all the logging with std::cerr > put behind an ifdef  and __LIBREMIDI_DEBUG__
- [x] allow users to plug-in their own custom logging back-end instead
- [x] backport the fixes that happened in RtMidi since then: 
    `git diff -w 6ad9c059ce895c44616bcfa8104ca94678bc9408  -- RtMidi.cpp RtMidi.h`
- [x] passing timestamps: https://github.com/jcelerier/libremidi/compare/master...wip/midi_write_ts 
- [x] observers: make sure that they all behave the same and stay coherent with what midi_in / midi_out says about the ports
- [ ] document the semantic of the ins / outs for each backend
- [ ] #74
   * alsa_raw 
   * coremidi
- [ ] #75
  - [x] alsa_raw
  - [x] alsa_seq
  - [ ] observers
- [x] refactor the observers and give them a context object too, to allow sharing the context with midi_in / midi_out
- [ ] #76
- [ ] thread-safety annotations with clang

Relevant: 
* [ ] Android support
* [x] iOS support (https://github.com/thestk/rtmidi/commit/d4972bcfaacfbdbb254b5d5546bd6b369e4f5f21 ; https://github.com/thestk/rtmidi/commit/15eff571e876ed149645f3c897e73ea9fee5cadb  https://github.com/thestk/rtmidi/commit/9d863beb28f03ec53f3e4c22cc0d3c34a1e1789b ) -> it already is done in libremidi :)
* [x] https://github.com/thestk/rtmidi/commit/13bac1059a40a21f3443ff1e51566c7a50a26dc2 (done)
* [x] ~https://github.com/thestk/rtmidi/commit/825c5a401a05389a7dad44c4a6b9e9bebeb43a07 ; https://github.com/thestk/rtmidi/commit/34b62f06e22f58164f512206ce5e840170d16570 ; https://github.com/thestk/rtmidi/commit/a96a9c51da5c93be669d4a66b9e323eb24eaa723~ instead of this, will document that one has to pass a pre-existing MIDIClient object to the library to be safe
* [x] https://github.com/thestk/rtmidi/commit/a34416888d88cf8f45063dc33cbcfaac7d1dca9b (done)
* [x] https://github.com/thestk/rtmidi/commit/d44cf4ab081b6f4231c4baaba5ad1987a8b03507 ; https://github.com/thestk/rtmidi/commit/fa8b91791e5ab561ba29053010992f7c1e4f5b23
* [x] https://github.com/thestk/rtmidi/commit/a4c7e13f9eac37ca24bd7bcec7709a52b5f6113c
* [x] https://github.com/thestk/rtmidi/commit/6e4e763a19860c17784992ff3170704ba73c10b7
* [x] https://github.com/thestk/rtmidi/commit/6ad9c059ce895c44616bcfa8104ca94678bc9408
* [x] https://github.com/thestk/rtmidi/commit/e6ba3e526d9612b5ec0b25c1fba02c255919fc8b
* [x] https://github.com/thestk/rtmidi/commit/83c681cd4484dc9e4e73d5fee1338fd1866cfeae (done)
* [x] https://github.com/thestk/rtmidi/commit/390286f1c39df6b8840dd034a5af672b1601d4b0 (done)
* [x] https://github.com/thestk/rtmidi/commit/cfe34c02112c256235b62b45895fc2c401fd874d
* [x] https://github.com/thestk/rtmidi/commit/fb46e088d9d1d5bf02f2fc6bc5f98542e081af57 (done)
* [x] https://github.com/thestk/rtmidi/commit/44c2ee69cfb57fec9e72d82180946db95889d4b0
- what else?

**Comment by jcalifa** [comment]
Not an API change, but it would be nice to get libremidi on vcpkg

**Comment by jcelerier** [comment]
closing as it's pretty much where I want it to be.. just have to finish the MIDI 2 backends =)
